
spring:
  application.name: chelidonium
  profiles.active: chelidonium,default

---
spring.profiles: chelidonium

server.port: 9292

management:
  endpoint.shutdown.enabled: true
  endpoints:
    web.exposure.include: '*'

chelidonium:
  aliyun:
    endpoints:
      shanghai: http://www.replace.me

    accessKey: 'replace me'
    secretKey: 'replace me'

  baseDir: C:\\Intel\\Logs
